import type { Metadata } from 'next'
import { Inter, Lexend_Deca } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'], weight: ["400", "700"] })
const lexendDeca = Lexend_Deca({subsets: ['latin'], weight: ["200", "300", "400"]})

export const metadata: Metadata = {
  title: 'Stats preview card component',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={lexendDeca.className}>{children}</body>
    </html>
  )
}
